apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - podinfo-fork-registry.yaml
  - podinfo-patch-policy.yaml
images:
  - name: ghcr.io/stefanprodan/podinfo
    newName: ghcr.io/hiddeco/podinfo # {"$imagepolicy": "flux-system:podinfo-patch:name"}
    newTag: 5.2.1-patch-1630930968 # {"$imagepolicy": "flux-system:podinfo-patch:tag"}
