name: Auto-PR (bar)
on:
  push:
    branches: ['bar']

jobs:
  pull-request:
    name: Open PR to main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "main"
        pr_title: "Pulling bar into main"
        pr_body: ""
        pr_draft: false
        github_token: ${{ secrets.GITHUB_TOKEN }}
